<label for="barsShow">show: </label>
<select id="barsShow">
<option value="true" selected="selected">true</option>
<option value="false">false</option>
</select>
<br>

<label for="barsLineWidth">lineWidth: </label><input type="text" value="2" id="barsLineWidth" size="3" /><br>

<label for="barsBarWidth">barWidth: </label><input type="text" value="0.4" id="barsBarWidth" size="3" /><br>

<label for="barsFill">fill: </label>
<select id="barsFill">
<option value="true" selected="selected">true</option>
<option value="false">false</option>
</select>
<br>

<label for="barsFillColor">fillColor: </label><input class="color" type="text" value="null" id="barsFillColor" size="7" /><br>

<label for="barsFillOpacity">fillOpacity: </label><input type="text" value="0.8" id="barsFillOpacity" size="3" /><br>

<label for="barsHorizontal">horizontal: </label>
<select id="barsHorizontal">
<option value="true">true</option>
<option value="false" selected="selected">false</option>
</select>
<br>

<label for="barsStacked">stacked: </label>
<select id="barsStacked">
<option value="true">true</option>
<option value="false" selected="selected">false</option>
</select>
<br>

<label for="barsCentered">centered: </label>
<select id="barsCentered">
<option value="true" selected="selected">true</option>
<option value="false">false</option>
</select>
<br>

<label for="barsTopPadding">topPadding: </label><input type="text" value="0.1" id="barsTopPadding" size="3" /><br>

<label for="barsGrouped">grouped: </label>
<select id="barsGrouped">
<option value="true">true</option>
<option value="false" selected="selected">false</option>
</select>
<br>
