<?
$divWidth = isSet($divWidth) ? $divWidth : 400;
$divHeight = isSet($divHeight) ? $divHeight : 400;
?>

<label for="divwidth">divwidth (in px): </label><input type="text" value="<?php echo $divWidth ;?>" id="divwidth" size="7" /><br>

<label for="divheight">divheight (in px): </label><input type="text" value="<?php echo $divHeight ;?>" id="divheight" size="7" /><br>

<label for="divbackground-color">divbackground-color: </label><input class="color" type="text" value="#f9f9f9" id="divbackground-color" size="7" /><br>


