<label for="legendShow">show: </label>
<select id="legendShow">
<option value="true" selected="selected">true</option>
<option value="false">false</option>
</select>
<br>

<label for="position">position: </label><input type="text" value="nw" id="position" size="3" /><br>

<label for="labelBoxBorderColor">labelBoxBorderColor: </label><input class="color" type="text" value="#cccccc" id="labelBoxBorderColor" size="7" /><br>

<label for="labelBoxWidth">labelBoxWidth: </label><input type="text" value="14" id="labelBoxWidth" size="3" /><br>

<label for="labelBoxHeight">labelBoxHeight: </label><input type="text" value="10" id="labelBoxHeight" size="3" /><br>

<label for="labelBoxMargin">labelBoxMargin: </label><input type="text" value="5" id="labelBoxMargin" size="3" /><br>

<label for="legendMargin">legendMargin: </label><input type="text" value="5" id="legendMargin" size="3" /><br>

<label for="legendBgOpacity">legendBgOpacity: </label><input type="text" value="0.85" id="legendBgOpacity" size="3" /><br>

<label for="backgroundColor">backgroundColor: </label><input class="color" type="text" value="#fff8b8" id="backgroundColor" size="7" /><br>

