<nav>
<ul>
<li><i class="fa fa-line-chart"></i> <a href="linegraph.php">Line Graph</a></li>
<li><i class="fa fa-bar-chart"></i> <a href="bargraph.php">Bar Graph</a></li>
<li><i class="fa fa-pie-chart"></i> <a href="piechart.php">Pie Chart</a></li>
<li><i class="fa fa-area-chart"></i> <a href="stacked-percentage.php">Stacked Percentage</a></li>
</ul>

<ul>
<li><i class="fa fa-line-chart"></i> <a href="TestPages/flotrLineTest.html">Line Test</a></li>
<li><i class="fa fa-bar-chart"></i> <a href="TestPages/flotrBarTest.html">Bar Test</a></li>
<li><i class="fa fa-pie-chart"></i> <a href="TestPages/flotrPieTest.html">Pie Test</a></li>
<li><i class="fa fa-area-chart"></i> <a href="TestPages/flotrStackedTest.html">Stacked Test</a></li>
</ul>
</nav>
