<label for="pieshow">show: </label>
<select id="pieshow">
<option value="true" selected="selected">true</option>
<option value="false">false</option>
</select>
<br>

<label for="explode">explode: </label><input type="text" value="0" id="explode" size="3" /><br>

<label for="sizeRatio">sizeRatio: </label><input type="text" value="0.7" id="sizeRatio" size="3" /><br>

<label for="pieFill">fill: </label>
<select id="pieFill">
<option value="true" selected="selected">true</option>
<option value="false">false</option>
</select>
<br>

<label for="pieFillOpacity">fillOpacity: </label><input type="text" value="0.8" id="pieFillOpacity" size="3" /><br>

<label for="lineWidth">lineWidth: </label><input type="text" value="2" id="lineWidth" size="3" /><br>

<label for="strokeColor">strokeColor: </label><input class="color" type="text" value="#ffffff" id="strokeColor" size="7" /><br>

<label for="startAngle">startAngle: </label><input type="text" value="0.754" id="startAngle" size="5" /><br>

