<label for="xShowLabels">showLabels: </label>
<select id="xShowLabels">
<option value="true" selected="selected">true</option>
<option value="false">false</option>
</select>
<br>

<label for="xShowMinorLabels">showMinorLabels: </label>
<select id="xShowMinorLabels">
<option value="true">true</option>
<option value="false" selected="selected">false</option>
</select>
<br>

<label for="xLabelsAngle">labelsAngle: </label><input type="text" value="0" id="xLabelsAngle" size="3" /><br>

<label for="xTitle">title: </label><input type="text" value="X axis" id="xTitle" size="25" /><br>

<label for="xTitleAngle">titleAngle: </label><input type="text" value="0" id="xTitleAngle" size="3" /><br>

