<label for="yShowLabels">showLabels: </label>
<select id="yShowLabels">
<option value="true" selected="selected">true</option>
<option value="false">false</option>
</select>
<br>

<label for="yShowMinorLabels">showMinorLabels: </label>
<select id="yShowMinorLabels">
<option value="true">true</option>
<option value="false" selected="selected">false</option>
</select>
<br>

<label for="yLabelsAngle">labelsAngle: </label><input type="text" value="0" id="yLabelsAngle" size="3" /><br>

<label for="yTitle">title: </label><input type="text" value="Y axis" id="yTitle" size="25" /><br>

<label for="yTitleAngle">titleAngle: </label><input type="text" value="90" id="yTitleAngle" size="3" /><br>

